# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170225_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='category.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='report',
            field=models.ManyToManyField(blank=True, null=True, to='category.Report'),
        ),
    ]
