# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20170225_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Report')),
            ],
        ),
    ]
