# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_reportprocedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='LocType',
        ),
    ]
