# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20170228_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_position', models.IntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Filter')),
                ('report_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.ReportProcedure')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='category.SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='report',
            field=models.ManyToManyField(blank=True, to='category.Report'),
        ),
        migrations.AlterUniqueTogether(
            name='reportfilter',
            unique_together=set([('filter', 'report_procedure', 'parameter_position')]),
        ),
    ]
